### ISSUE TITLE
Importing a Paper Server crashes Nihilus, and crashes Nihilus anytime it starts up

### ISSUE THREAD

**Issue by anthonymendez** [ChristianKern97/nihilus#5]
To reproduce, create, or use an existing paper server.
Use default settings an import.
Stuck on downloading server jar for a bit but it eventually loads everything.
Once program loads, Nihilus will crash.
Any attempts to re-open Nihilus, will work for a second but then just crash.

Tested on my Windows Server 2019 machine.

**Comment by anthonymendez** [comment]
I recorded a video of this one.

[https://www.youtube.com/watch?v=8eqqE8m541E](https://www.youtube.com/watch?v=8eqqE8m541E)

Give the video a few minutes to process.

**Comment by ChristianKern97** [comment]
How many players are in the worlds playerdata?

**Comment by anthonymendez** [comment]
25 Players. Sorry for the long response time.

**Comment by ChristianKern97** [comment]
This issue also needs error log

**Comment by anthonymendez** [comment]
Don't see the issue anymore when running on my server.
